rootProject.name = "stringconcat-carsharing"

include(":mainApp")
include(":commons:ddd-types")
include(":commons:value-objects")
include(":purchasing-department:domain")
include(":purchasing-department:usecase")
include(":purchasing-department:persistence")
include(":maintenance:domain")
include(":maintenance:usecase")
include(":maintenance:persistence")
include(":customer:domain")
include(":customer:usecase")
include(":customer:persistence")
include(":ride:domain")
include(":ride:usecase")
include(":ride:persistence")
include(":application")
include(":integration:gis-gmp")
include(":integration:acquirer")