comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

style:
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    excludeImports: [ ]
    active: true
  FunctionOnlyReturningConstant:
    active: false
  UnnecessaryAbstractClass:
    active: false

formatting:
  active: true
  android: false
  autoCorrect: true
  FinalNewline:
    active: false
  ImportOrdering:
    active: false
    autoCorrect: true
    layout: '*,java.**,javax.**,kotlin.**,^'
  NoEmptyFirstLineInMethodBlock:
    active: false
    autoCorrect: true

naming:
  InvalidPackageDeclaration:
    active: false
    excludes: [ '*.kts' ]
  MatchingDeclarationName:
    active: true
    excludes: [ '**/testFixtures/**/Fixtures.kt',  '**/test/**/Fixtures.kt' ]

performance:
  SpreadOperator:
    active: false

complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true