name: Build feature branch

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: Build-feature-branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images
        id: build-images
        run: |
          ./buildAll.sh $IMAGE_TAG
        continue-on-error: true

      - name: Upload reports
        id: upload-reports
        if: steps.build-images.outcome != 'success'
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ./**/**/build/reports
            ./mainApp/build/reports
            !./buildSrc/build/reports

      - name: Publish unit tests result
        id: publish-unit-tests-result
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        with:
          report_individual_runs: true
          files: ./**/build/test-results/**/*.xml

      - name: Check on build failures
        if: steps.build-images.outcome != 'success'
        run: exit 1