name: Build feature branch

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: Build-feature-branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images
        id: build-images
        run: |
          ./buildAll.sh $IMAGE_TAG
        continue-on-error: true

      - name: Upload detekt artifact
        id: upload-detekt-artifact
        if: steps.build-images.outcome != 'success'
        uses: actions/upload-artifact@v2
        with:
          name: mainApp-detekt
          path: ${{ github.workspace }}/mainApp/build/reports/detekt/detekt.html

      - name: Upload jacoco artifact
        id: upload-jacoco-artifact
        if: steps.build-images.outcome != 'success'
        uses: actions/upload-artifact@v2
        with:
          name: mainApp-jacoco
          path: ${{ github.workspace }}/mainApp/build/reports/jacoco/test/html

      - name: Upload tests artifact
        id: upload-tests-artifact
        if: steps.build-images.outcome != 'success'
        uses: actions/upload-artifact@v2
        with:
          name: mainApp-tests
          path: ${{ github.workspace }}/mainApp/build/reports/tests/test

      - name: Check on build failures
        if: steps.build-images.outcome != 'success'
        run: exit 1